async function sendMessage() {
  const textInput = document.getElementById("userInput");
  const fileInput = document.getElementById("mediaInput");
  const chat = document.getElementById("chatBox");

  const text = textInput.value.trim();
  const file = fileInput.files[0];

  // Nothing sent
  if (!text && !file) {
    alert("Please type a prompt or upload image/video");
    return;
  }

  // Show user message
  chat.innerHTML += `<p><b>You:</b> ${text || "Uploaded media"}</p>`;
  chat.innerHTML += `<p><b>CaptionCraft AI:</b> Thinking... ✨</p>`;

  // RESET INPUT
  textInput.value = "";
  fileInput.value = "";

  // ===== DEMO AI RESPONSE (for now) =====
  setTimeout(() => {
    chat.innerHTML += `
<b>Caption 1 (Short & Catchy):</b><br>
Moments that deserve more than just a scroll ✨<br><br>

<b>Caption 2 (Medium):</b><br>
Turning visuals into viral stories with AI 🚀📸<br><br>

<b>Caption 3 (Long / Story Style):</b><br>
Every image or video holds a story, and CaptionCraft AI brings it to life with words that connect, inspire, and engage 💫<br><br>

<b>Hashtags:</b><br>
#CaptionCraftAI #AICaptions #ReelsIndia #ContentCreator #SocialMediaGrowth #ViralContent #AItools #TrendingNow<br><br>

Generated by CaptionCraft AI ✨
`;
  }, 1200);
}
