function sendMessage() {
  const input = document.getElementById("userInput");
  const chat = document.getElementById("chatBox");

  if (input.value === "") return;

  chat.innerHTML += `<p><b>You:</b> ${input.value}</p>`;
  chat.innerHTML += `<p><b>CaptionCraft AI:</b> Thinking... ✨</p>`;

  setTimeout(() => {
    chat.innerHTML += `
<b>Caption 1 (Short & Catchy):</b><br>
Create magic with every post ✨<br><br>

<b>Caption 2 (Medium):</b><br>
Turning moments into scroll-stopping captions 🚀<br><br>

<b>Caption 3 (Long / Story Style):</b><br>
Every image tells a story, and we help you tell it beautifully 📸💫<br><br>

<b>Hashtags:</b><br>
#CaptionCraftAI #AIcaptions #ReelsIndia #ContentCreator #SocialMediaGrowth #ViralPosts #AItools #TrendingNow<br><br>

Generated by CaptionCraft AI ✨
`;
  }, 1200);

  input.value = "";
}
async function sendMessage() {
  const input = document.getElementById("userInput").value;
  const chat = document.getElementById("chatBox");

  chat.innerHTML += `<p><b>You:</b> ${input}</p>`;
  chat.innerHTML += `<p><b>CaptionCraft AI:</b> Thinking...</p>`;

  const response = await fetch(
    "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=AIzaSyCmZfez4Zrivvkyh_1DtevKYbjxJj28MS0,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{ parts: [{ text: input }] }]
      })
    }
  );

  const data = await response.json();
  chat.innerHTML += `<p>${data.candidates[0].content.parts[0].text}</p>`;
}
