function sendMessage() {
  const input = document.getElementById("userInput");
  const chat = document.getElementById("chatBox");

  if (input.value === "") return;

  chat.innerHTML += `<p><b>You:</b> ${input.value}</p>`;
  chat.innerHTML += `<p><b>CaptionCraft AI:</b> Thinking... ✨</p>`;

  setTimeout(() => {
    chat.innerHTML += `
<b>Caption 1 (Short & Catchy):</b><br>
Create magic with every post ✨<br><br>

<b>Caption 2 (Medium):</b><br>
Turning moments into scroll-stopping captions 🚀<br><br>

<b>Caption 3 (Long / Story Style):</b><br>
Every image tells a story, and we help you tell it beautifully 📸💫<br><br>

<b>Hashtags:</b><br>
#CaptionCraftAI #AIcaptions #ReelsIndia #ContentCreator #SocialMediaGrowth #ViralPosts #AItools #TrendingNow<br><br>

Generated by CaptionCraft AI ✨
`;
  }, 1200);

  input.value = "";
}
